#ACCION HEROICA
POPULARIDAD_ACCION_HEROICA = 5
ENERGIA_ACCION_HEROICA = 5

#PEDIR OBJETO
COSTO_OBJETO = 5
POPULARIDAD_PEDIR = 5

#ATACAR TRIBUTO
ENERGIA_ATACAR = 5
POPULARIDAD_ATACAR = 5

#HACERSE BOLITA
ENERGIA_BOLITA = 5

#EVENTOS
PROBABILIDAD_EVENTO = 0.5

#PLAYA
VELOCIDAD_VIENTOS_PLAYA = 18
HUMEDAD_PLAYA = 50

#MONTAÑA
NUBOSIDAD_MONTAÑA = 12
PRECIPITACIONES_MONTAÑA = 24

#BOSQUE
PRECIPITACIONES_BOSQUE = 32
VELOCIDAD_VIENTOS_BOSQUE = 22

#CONSUMIBLE
AUMENTAR_ENERGIA = 5
PONDERADOR_AUMENTAR_ENERGIA = 5

#ARMA 
PONDERADOR_AUMENTAR_FUERZA = 5

#ESPECIAL
AUMENTAR_AGILIDAD = 5
AUMENTAR_INGENIO = 5
