DEUDA_TOTAL = 10000
PROBABILIDAD_EVENTO = 0.5
MIN_ENERGIA_BEBESTIBLE = 5
MAX_ENERGIA_BEBESTIBLE = 10

FRUSTRACION_PERDER = 1
CONFIANZA_PERDER = 1
EGO_GANAR = 1
CARISMA_GANAR = 1
FRUSTRACION_GANAR = 1



PORCENTAJE_APUESTA_TACANO = 1
BONIFICACION_TACANO = 1

MULTIPLICADOR_BONIFICACION_BEBEDOR = 1

BONIFICACION_SUERTE_CASUAL = 1   